#!/usr/bin/env bash
set -e

# Example of usage:
# gh accepted nextjs ULL-ESIT-DMSI-2324
# Assignment: nextjs 
# ID: 514042 

# ID        Submitted  Passing  Commit Count  Grade  Feedback Pull Request URL  Student            Repository
# 12655694  false      false    1                                               casiano-rodriguez  https://github.com/ULL-ESIT-DMSI-2324/nextjs-casiano-rodriguez-leon-alu0100291865
# 12789698  false      false    13                                              ShayBRJ            https://github.com/ULL-ESIT-DMSI-2324/nextjs-borja-medina-ramos-alu0101337609
# 12789701  false      false    16                                              Konobono           https://github.com/ULL-ESIT-DMSI-2324/nextjs-konrad-jan-pierzchlewicz-alu0101686226
# 12789715  false      false    15                                              DanMAMO            https://github.com/ULL-ESIT-DMSI-2324/nextjs-daniel-marichal-monsonis-alu0101014548

function usage() {
    echo "Usage: gh accepted <classroom assignment name> [organization]"
    echo "Description: List of github classroom accepted assignments"
}
# if option is -h or --help, then show help
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
    exit 0
fi
if [ -z "$1" ]; then
    usage
    exit 1
fi
CLASSROOMPATTERN=$1
ORGANIZATION=$(gh pwd)
if [ -n "$2" ]; then
  ORGANIZATION=$2
fi
CLASSROOM=$(gh classroom list --per-page 200 | grep $ORGANIZATION | awk '{print $1}')
if [ -z "$CLASSROOM" ]; then
    echo "No classroom \"$ORGANIZATION\" found"
    exit 1
fi
ASSIGNMENTID=$(gh classroom assignments --per-page 200  -c $CLASSROOM | grep -i $CLASSROOMPATTERN | awk '{print $1}')
if [ -z "$ASSIGNMENTID" ]; then
    echo "No assignment \"$CLASSROOMPATTERN\" found"
    exit 1
fi
RESULT=$(gh classroom accepted-assignments -a $ASSIGNMENTID)
echo "$RESULT"

